# kubetmp/fortune-deploy.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deployment
  labels:
    app: fortune
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - image: dangtong/fortune
        name: html-generator # container1
        volumeMounts:
        - name: html
          mountPath: /var/htdocs # 해당 디렉토리에 명언 작성(-> fortuneloop.sh)
      - image: nginx:alpine
        name: web-server # container2
        volumeMounts: # 이 구문에서 쓰기 시작
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
          - containerPort: 80
            protocol: TCP
      volumes: # 이 구문에서 volume을 정의하고
      - name: html
        emptyDir: {}