apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo-pod
spec:
  containers:
  - name: liveness-demo
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3